upstream backend_servers {
    server ${APP_TARGET_IP}:8081;
}

server {
    listen 80;
    server_name miprovector.com;

    location / {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Deployment-Color Green always;
        return 200 "Ambiente Green activo";
    }
}